image: nixos/20.03
sources:
  - https://git.sr.ht/~hauleth/BARE-Erlang
tasks:
  - proper: |
      cd BARE-Erlang
      nix-shell --command 'rebar3 proper'
  - mirror: |
      if [ ! -z "$GITHUB_PR_NUMBER" ]; then exit 0; fi
      echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' >> ~/.ssh/known_hosts
      cd BARE-Erlang
      git push --force --all git@github.com:hauleth/bare-erlang
secrets:
  - 09541416-1854-4c53-994b-2c46ba86306b
